name: Build WF
on:
  push:
    branches:
    - main

  pull_request:
    branches: 
    - main

  workflow_dispatch:
  
  schedule:
    - cron: '10 14 * * 1-5'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Maven Build
      run: mvn install
    
    - name: upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: target/*.war
    
    - name: notify if build fails
      if: failure()
      run: echo "Build failed! Please check the logs."

    - name: notify if build succeeds
      if: success()
      run: echo "Build succeeded! Artifact uploaded."
      
  
  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run test on maven branch
        run: mvn test
      
      - name: checkstyle
        run: mvn checkstyle:checkstyle