name: Build WF
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: Maven Build
      run: mvn install
  
  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: run test on maven branch
        run: mvn test
      
      - name: checkstyle
        run: mvn checkstyle:checkstyle